# Brisbane's Environment

The Brisbane Local Government Area (LGA) is home to many varied habitat types. Dominated by the urban footprint of Brisbane City and surrounding suburbs, the majority of land in the LGA is non-remnant habitat covered by houses, infrastructure and provides limited opportunity for most wildlife to thrive. It is in the city's many parks, both natural and man-made, that birdlife abounds.

The coastline of Moreton Bay to the east of the city is dominated by estuarine mangrove forests and mudflats, which play host to 50,000 migratory shorebirds each year, as well as providing habitat for several other cryptic species within the city. Sites such as Tinchi Tamba Wetlands, Kedron Brook Wetlands and Sandy Camp Road all cater to a significant variety of bird species; each of these three sites have over 200 recorded species.

To the north west of the city, the foothills of the D'Aguilar Range slope steadily up towards Mount Nebo and Mount Glorious, and are home to the majority of the area's subtropical rainforest. Slightly further south, the Taylor Range and its peak, Mt Coot-tha, is covered in mixed sclerophyll habitat. Together, these two ranges combine to form a vast area of prime forest habitat that for the most part is poorly covered by birders.

Moving further south, the extreme south west of the region is mostly flat, and is dominated by sparse semi-rural farmland with pockets of remnant habitat. Dry eucalpyt forest covers the western border with Somerset Regional Council near Lake Manchester, while grassy scrub accounts for much of the remaining ground cover. This is an area of Brisbane rarely visited by birders and locals alike, despite sites such as Moggill Conservation Park and Lake Manchester being some of the richest birdlife hotspots in South East Queensland.

The majority of the south and south east section of Brisbane City Council is non-remnant vegetation or housing, with only restricted pockets of bushland and consequently limited variety of birdlife. This said, some areas of suburbia are much richer than others, and _Atlas_ is playing a part in documenting why this is so. Bushland reserves in Toohey Forest, Whites Hill and Belmont make up the greatest part of the green space encapsulated by suburban development, although there are numerous smaller parks and reserves which provide limited habitat for some bird species. Despite this area containing some of the most densely populated suburbs in Brisbane, on the whole it lacks birding coverage, in part due to the paucity of obvious locations for birding and in part due to preferences among birders to visit well-established birding hotspots in other areas of the city. Suburban parks can turn up avian surprises, and eBird checklists can be submitted while visiting such places for other purposes, e.g. a social gathering.

Finally, across Moreton Bay lies Moreton Island, a 186km^2^ sand island that shelters the bay from the worst of the Coral Sea's weather and provides habitat for many species of bird that are absent or vanishingly rare on the mainland. The north end of the island is predominately heath, a habitat not found on the mainland, while the south is coastal scrub and dry eucalpyt forest. Together with the extensive sandy coastline that surrounds nearly the entire island, there is habitat for nearly 150 species of birds. This number would no doubt be higher with increased birding activity and detection, but due to access difficulty, Moreton Island remains undoubtedly the least birded region within Brisbane City Council. There surely remains much to be discovered on this isle.

Alogether, just under 400 bird species have been recorded in Brisbane has, with several new species being added each year. Increased activity around the edges of the area, particularly in locations such as Lake Manchester and Moreton Island, is sure to increment this number steadily upwards, highlighting just how fantastic a biodiversity hotspot our city is.
