# Contributing

Here are all the ways you can contribute to this _Atlas_!

1. Go birdwatching in the city of Brisbane (see [here](http://www.dlgrma.qld.gov.au/resources/map/reform/brisbane-map.pdf) for a map) and enter your observations on [eBird](http://www.ebird.org), a free online tool for recording bird observations. All eBird records for Brisbane will be automatically included in the _Atlas_. Breeding records are especially needed at the moment, so please make sure you note down using eBird's breeding codes system any birds you see breeding!

2. If you have old records stored away on notebooks and such, enter them into eBird too! See [here](https://help.ebird.org/customer/en/portal/articles/973960-entering-historic-data) on more information about entering historic data into eBird. If you want any help with importing your records, email [Richard Fuller](mailto:r.fuller@uq.edu.au) to discuss - we will be glad to help you, or even to fully manage the task on your behalf and get you set up on eBird.

3. If you have taken any better images than those already used as the header photo in a species account, please consider contributing them to the _Atlas_. The photo must have been taken in Brisbane, and should be cropped to 16:9. The image will be licensed in the public domain, hosted on the [Atlas Flickr site](https://www.flickr.com/photos/159495711@N04/), and always used with proper attribution to the photographer in the _Atlas_ - email it to [Richard Fuller](mailto:r.fuller@uq.edu.au).

4. Write some text for the _Atlas_, or edit and improve some of the existing text. See [here](https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#how-can-i-contribute-to-this-atlas) for details. Full instructions on how to edit _Atlas_ pages will be available from 1 January 2019 onwards. The Github repository and associated wiki have plenty of information on how to contribute text or back-end changes. If you would like further clarification or assistance, feel free to contact one of the _Atlas_ administrators or [create an issue on the repository](https://github.com/bird-team/brisbane-bird-atlas/issues/new/choose).

5. If you have any suggestions for content, or information about Brisbane's birds that you think would be helpful for the _Atlas_, please contact the editors. Email [Richard Fuller](mailto:r.fuller@uq.edu.au), or create an issue on the [GitHub Repository](https://github.com/bird-team/brisbane-bird-atlas/issues).

The _Atlas_ project is still very much under active construction and is not yet ready for public contributions. Please check the [index page](https://brisbanebirds.com/index.html) for exciting updates to the atlas - we anticipate an official launch on 1 January 2019, so be sure to visit then. In the meantime, go out and bird! The _Atlas of Brisbane Birds_ uses data pulled from [eBird](https://ebird.org/home). If you would like to have your records be added to the _Atlas_ all you need to do is ensure that they are entered into eBird - the rest is done automatically. Check out [how to make the most of your eBird checklists](https://help.ebird.org/customer/portal/articles/974012) to ensure the data going into the Atlas - and any other projects which use eBird data - are as good as possible.

Currently, the atlas lacks a lot of information for the breeding activity of most species - so if you see any breeding behaviour in the birds you report, please add it in using the [eBird breeding codes](https://help.ebird.org/customer/portal/articles/1006850-breeding-codes-behavior-codes)! Additionally, check out the surveyor sheets to find Atlas squares with very little - or even no - data to their name, and go and bird in these areas. Some of them are in prime birding habitat, so who knows how many birds you could find!

The _Atlas_ project endorses ethical birding. The welfare of our birds is the highest priority so please engage in birding practices which do not adversely impact the birds around you. Nesting and migratory birds are particularly vulnerable to disturbances.

**Future Update Goals**

- Complete species accounts for all recorded Brisbane bird species
- Grid square survey sheets for every cell
- More comprehensive data for all species, particularly poorly known ones e.g. seabirds and breeding information
