# Gazetteer

Brisbane's birdlife is varied and abundant. All across the region there are sites which host scores of species. This page is intended to showcase some of the very best birding hotspots Brisbane has to offer. Initially, this comprises the top 40 [eBird](https://ebird.org/home) hotspots in Brisbane:

**[1. Tinchi Tamba Wetlands Reserve](https://ebird.org/australia/hotspot/L960635)**  
238 Species | [27°17'56.9"S 153°02'12.0"E](https://goo.gl/maps/sjWBv5DSmoT2)  
Brisbane's most abundant birding hotspot, the Tinchi Tamba Wetlands are a large expanse of intertidal mudflats and wetlands in the far north of the city. The mudflats provide a high tide roost for dozens of wader species, including rare vagrant shorebirds such as Buff-breasted Sandpiper, Ruff, Long-toed Stint and Pectoral Sandpiper. The freshwater lagoons offer a different habitat and consequently have different birds, including on occasion Brolga, Black-Necked Stork, Little Grassbird and Australian Spotted Crake, all rare species within the Brisbane boundary.  
Local Experts: Ged Tranter, Steve Murray, Rick Franks.

**[2. Oxley Creek Common](https://ebird.org/australia/hotspot/L967148)**  
216 Species  |  [27°32'09.2"S 152°59'34.2"E](https://goo.gl/maps/pDD3an4XLg12)  
By far Brisbane's most visited birding location, Oxley Creek Common is a vast expanse of grazing fields, woodland and wetlands nestled between the industrial suburbs of Rocklea, Oxley and Sherwood in the inner south west of the city. As many as 70 species of bird can be found in one hour at the Common, including the odd rarity. Brown Quails are a staple and can be easily found scurrying in large groups along the side of the path - a favourite of many visiting birders.  
Local Experts: Hugh Possingham, Mat Gilfedder.

**[3. Sandy Camp Road Wetlands](https://ebird.org/australia/hotspot/L1788977)**  
208 Species | [27°26'05.8"S 153°08'50.4"E](https://goo.gl/maps/kxuEihD44V12)  
Another very popular site within Brisbane, Sandy Camp is a large area of freshwater wetlands in the middle of the industrial centre east of Brisbane. Crakes and Rails are highly sought after here, and can be found early most mornings in the reeds fringing the ponds. Australian Little Bitterns are very secretive but are present at the site over summer, and Black Bitterns are rare visitors and are very difficult to find.  
Local Experts: Chris Attewell, Richard Miller, Andrew Naumann.

**[4. Lake Manchester](https://ebird.org/australia/hotspot/L2558202)**  
205 Species | [27°29'23.8"S 152°44'44.0"E](https://goo.gl/maps/RwiU3siiF3p)  
Much less visited than the sites above, Lake Manchester makes up for a lack of popularity with a plethora of birds. Situated on the far west edge of Brisbane out near Ipswich, Lake Manchester provides habitat for many inland birds not found anywhere else in the region. It is one of the best sites in Brisbane for nocturnal birds, with Powerful Owl, Southern Boobook, Australian Owlet-Nightjar, White-throated Nightjar and Barn Owl all being commonly encountered at night. King Quail are a scarce resident among rank grasses fringing the lake and nearby Cabbage Tree Creek, and the site has played host to a large number of rare inland birds, particularly during dry years in the interior.  
Local Experts: Richard Fuller, Ged Tranter, Steve Murray.

**[5. Kedron Brook Wetlands Reserve](https://ebird.org/australia/hotspot/L1176744)**  
200 Species | [27°24'03.7"S 153°04'45.7"E](https://goo.gl/maps/HDzBGFjrUzv)  
Another fantastic set of wetlands in the coastal region of Brisbane are the Kedron Brook Wetlands, situated by the banks of Kedron Brook at the end of Toombul Rd. Perhaps best known to Brisbane birders as being by far the most reliable site for Australasian Grass-Owls in the city, the wetlands are also home to many other rare and enchanting birds. Shorebirds are common in summer, with Sharp-tailed Sandpipers being the most abundant migratory bird, although rare Brisbane vagrants also turn up. The site is also particularly good for raptors, and notably has recorded Black Falcons on many occasions, as well as most other Brisbane birds of prey.  
Local Experts: Dezmond Wells, Steve Murray, Chris Attewell, Louis Backstrom.

**[6. Gold Creek Reservoir](https://ebird.org/australia/hotspot/L976352)**  
199 Species | [27°27'46.3"S 152°53'00.1"E](https://goo.gl/maps/gAVcZZxZsA42)  
A favourite spot for rainforest birding in Brisbane, Gold Creek Reservoir is a small dam situated in Upper Brookfield that is surrounded by prime lowland rainforest and wet sclerophyll habitat. The site is home to a number of species scarcely found eslewhere in Brisbane, including Crested Shrike-tit, Barred Cuckooshrike (in summer) and even the elusive Black-breasted Buttonquail, although the latter has not been recorded in several years. It is also one of the best locations in Brisbane to find Grey Goshawks, although the birds are quite unreliable.  
Local Experts: Chris Burwell, Jo Culican.

**[7. Dowse Lagoon](https://ebird.org/australia/hotspot/L1896576)**  
198 Species | [27°18'57.2"S 153°03'44.1"E](https://goo.gl/maps/koVnv3mKjMv)  
Another prolific wetland hotspot on Brisbane's northside, Dowse Lagoon is a large brackish lake covered in lily pads and home to a large variety of waterbirds. Magpie Geese are common here, and this is the most reliable spot in Brisbane for Cotton Pygmy-Goose, although the species is still rare. Latham's Snipe, Plumed Whistling-Duck and Comb-crested Jacana are also found here regularly, and in the past the site has had Wood Sandpiper, White-winged Black Tern and Eastern Yellow Wagtail turn up as rare vagrants.  
Local Experts: Ged Tranter, Steve Murray, Rick Franks.

**[8. Anstead Bushland Reserve](https://ebird.org/australia/hotspot/L974746)**  
195 Species  |  [27°32'35.0"S 152°51'40.1"E](https://goo.gl/maps/MihLcMFoZ2U2)  
A large area of woodland habitat in Brisbane's west, Anstead Bushland Reserve is a site where anything can turn up. Along with hosting a good variety of inland birds not found commonly elsewhere in Brisbane, the hotspot has recorded vagrants such as Red Wattlebird, Red-winged Parrot, Red-rumped Parrot, and Regent Honeyeater.  
Local Experts: Rod Gardner.

**[9. Lytton Wader Roost and Wynnum Mangrove Boardwalk](https://ebird.org/australia/hotspot/L1177500)**  
195 Species | [27°25'20.6"S 153°10'03.7"E](https://goo.gl/maps/1LuTrVvQDbn)  
The Lytton Wader Roost is a large claypan near the Wynnum Mudflats that holds large numbers of shorebirds at high tide when they come into roost. The nearby Wynnum Mangrove Boardwalk is a good spot for finding the birds at low tides as they feed out on the mudflats, as well as for mangrove specialist species such as Torresian Kingfisher, Mangrove Gerygone and Mangrove Honeyeater. The roost is an excellent spot for Pied Stilt, Chestnut Teal, Common Greenshank and Grey-tailed Tattler, among other species, and has in the past had vagrants visit including Asian Dowitcher, White-winged Black Tern, Long-toed Stint and Ruff.  
Local Experts: Matteo Grilli.

**[10. Minnippi Parklands](https://ebird.org/australia/hotspot/L1161973)**  
190 Species | [27°28'59.5"S 153°06'53.9"E](https://goo.gl/maps/f7LgSbDY4HT2)  
A productive area of parkland to the south east of the city, Minnippi is a varied area with wetlands, forest and grassy verges and hosts a large variety of species. In the past the site has turned up rare vagrants including Freckled Duck, Spotted Harrier, Sooty Tern (following Cyclone Oswald) and Scaly-breasted Munia.  
Local Experts: Stuart Pickering.

**[11. Boondall Wetlands Reserve](https://ebird.org/australia/hotspot/L921912)**  
189 Species  |  [27°20'25.8"S 153°04'40.8"E](https://goo.gl/maps/jBRzTZogJS32)  
A large area of mangroves and coastal paperbark forest in Brisbane's north east, the Boondall Wetlands have long been protected as an important site for Moreton Bay's migratory birds. While not as intensely birded as some of the other major wetland sites along the coast, Boondall nonetheless has many species of birds that call it home. Migratory shorebirds roost along the banks of mangrove-lined creeks, while common woodland birds call in the trees behind. This is one of the best locations in Brisbane for Shining Flycatcher, but these birds are not easy to find hidden among the mangroves.  
Local Experts: Steve Murray, Rick Franks, Felicia Chan.

**[12. D'Aguilar National Park - Araucaria Circuit](https://ebird.org/australia/hotspot/L2177590)**  
181 Species | [27°26'27.7"S 152°55'16.7"E](https://goo.gl/maps/a2Ni6StXqht)  
Enoggera Reservoir, situated to in The Gap in the west of Brisbane, is one of the most varied sites in Brisbane. Araucaria Circuit covers the north east section of the dam, starting and finishing at the Walkabout Creek Discovery Centre. The reservoir is one of the best locations in Brisbane for White-bellied Cuckooshrike, Crested Shrike-tit and Hardhead, with the latter being found in vast numbers across the lake. Rare vagrants or difficult species that have occurred at the site include Regent Honeyeater, Black-breasted Buttonquail, Musk Duck and Dusky Woodswallow.  
Local Experts: Colin Reid, Brad Woodworth, Steve Murray, Lucas Brook.

**[13. Nudgee Beach Reserve](https://ebird.org/australia/hotspot/L1172123)**  
178 Species  |  [27°20'39.8"S 153°05'53.2"E](https://goo.gl/maps/mcA3bxK56RR2)  
A large area of mudflats on the edge of Moreton Bay to the north east of the city, Nudgee Beach is adjacent to Boondall Wetlands and hosts thousands of migratory shorebirds each year. Bar-tailed Godwits, Curlew Sandpipers, Red-necked Stints and Pacific Golden-Plovers are all common here. Rarer shorebirds have turned up on occasion but nothing of major significance. The site is also excellent for Little Terns in summer, with counts of over 100 recorded.  
Local Experts: Malcolm Graham, Louis Backstrom, Matteo Grilli.

**[14. Prior's Pocket](https://ebird.org/australia/hotspot/L2558779)**  
177 Species  |  [27°35'45.9"S 152°53'59.2"E](https://goo.gl/maps/QjrD5spexYx)  
On the upper banks of Brisbane River near the Moggill Ferry crossing is Prior's Pocket, a Brisbane City Council Park that has a rich variety of birdlife. Yellow-rumped Thornbill, Brown and Rufous Songlark, Yellow-billed Spoonbill and various Woodswallow species are all rare Brisbane birds which occur relatively commonly at Prior's Pocket, and even rarer birds such as Freckled Duck, Hoary-headed Grebe, Spotted Harrier, Red-backed Kingfisher and Red-backed Buttonquail have occurred - anything can turn up at Prior's Pocket. Be sure to look up every once in a while too, as raptors are common circling overhead. - Black and Black-shouldered Kites feature commonly.  
Local Experts: Rod Gardner.

**[15. Shelley Road Park](https://ebird.org/australia/hotspot/L5769634)**  
170 Species  |  [27°29'29.7"S 152°44'35.8"E](https://goo.gl/maps/MSufNbPNDLo)  
Situated an the extreme west edge of Brisbane across the road from Lake Manchester, Shelley Road Park is an area just being discovered by Brisbane's birders. A large area of open woodland, grassy fields and muddy verges of the upper Brisbane River, the site's species list is rapidly incrementing and has turned up numerous rare vagrants including Black Falcon, Red-backed Kingfisher and four species of Woodswallow. One of the best locations in Brisbane for birds of prey, with 13 hawk, 3 owl and 5 falcon species having been recorded, many of which are resident at the site. It may be a long way from the city, but it's worth the drive out to Shelley Road, as anything can turn up on any given day.  
Local Experts: Richard Fuller.

**[16. Port of Brisbane Island](https://ebird.org/australia/hotspot/L2559161)**  
164 Species  |  [27°22'43.6"S 153°10'29.3"E](https://goo.gl/maps/52R3QPttp2R2)  
The Port of Brisbane, situated on Fisherman Island at the mouth of the Brisbane River, is a bustling port with large amounts of industrial activity, but is somewhat unique among busy ports in that it has numerous areas dedicated to birds and their environment. The Port of Brisbane has a large shorebird roost (encompassed by a [separate eBird hotspot](https://ebird.org/australia/hotspot/L984917)) as well as [several large lakes](https://ebird.org/australia/hotspot/L1367805) but the rest of the island also hosts a great variety of species. Access to the island itself is straightforward - the Port of Brisbane Motorway leads right there - but access into the majority of areas in the Port is strictly controlled due to maritime regulations. Contact the [Port Office](https://www.portbris.com.au/) for advice on access to such areas.  
Local Experts: Richard Miller, Rae Clark.

**[17. Fitzgibbon Bushland](https://ebird.org/australia/hotspot/L2559485)**  
163 Species | [27°20'07.6"S 153°01'41.2"E](https://goo.gl/maps/dVhaia4LFSG2)  
An area of preserved bushland situated in the modern Fitzgibbon Chase estate, Fitzgibbon Bushland hosts a wide variety of species and has turned up a number of interesting birds over the years. It has been in recent times one of the best locations in Brisbane for Painted Buttonquail, although the birds are still very cryptic and difficult to find. Other local specialties include Little Wattlebird (scarce throughout much of mainland Brisbane), Common Cicadabird and Grey Goshawk. Many species turn up for a short while and then disappear again, so be sure to check back regularly at the site for new birds.  
Local Experts: Ged Tranter, Ross Smith.

**[18. Kianawah Road Wetland](https://ebird.org/australia/hotspot/L2278383)**  
161 Species | [27°26'50.6"S 153°08'25.5"E](https://goo.gl/maps/BKdt8fKCNBU2)  
Just down the road from Sandy Camp, these wetlands are smaller than their more famous neighbour but nonetheless host a wide variety of birdlife and have an equal capacity for vagrants to occur. Red-kneed and Black-fronted Dotterels are common here, and this is one of the better locations in Brisbane to find Red-necked Avocets. Past rarities include Ruff, Plum-headed Finch, Painted Honeyeater and Pectoral Sandpiper.  
Local Experts: Chris Attewell.

**[19. Moggill Wetlands](https://ebird.org/australia/hotspot/L2558803)**  
160 Species  |  [27°35'12.2"S 152°51'37.4"E](https://goo.gl/maps/mbqFHNLizkL2)  
A small area of wetlands near the end of Moggill Road at the Moggill Ferry, this site has much to offer despite its small size. Like other western Brisbane hotspots, numerous inland vagrants have turned up over the years, including Hoary-headed Grebe, Freckled Duck and Red-rumped Parrot. Other good birds turn up more regularly, such as Yellow-billed Spoonbill (rare in Brisbane), White-necked Heron, White-bellied Cuckooshrike and Plumed Whistling-Duck.  
Local Experts: Rod Gardner, Jo Culican.

**[20. Tingalpa Creek Reserve](https://ebird.org/australia/hotspot/L2559604)**  
160 Species | [27°33'03.7"S 153°10'20.1"E](https://goo.gl/maps/sTmxiiKeVqN2)  
This hotspot, which includes the nearby JC Trotter Memorial Reserve, is a scarcely-birded section of bushland on the south edge of Tingalpa Reservoir near the border with Redland City Council. Similar to nearby wetland/bushland hotspots, it boasts a wide variety of birds, with waterbirds and passerines being represented in good numbers. Australasian Grebes are common here (and there are also several records of Great-Crested), as well as Comb-crested Jacana, Royal Spoonbill and many species of honeyeater. Past rarities have included Yellow-billed Spoonbill, Cotton Pygmy-Goose and Red Wattlebird.  
Local Experts: Colin Reid.

**[21. Metroplex Wetlands](https://ebird.org/australia/hotspot/L1177484)**  
159 Species  |  [27°27'12.7"S 153°06'03.6"E](https://goo.gl/maps/kzTedgzr66P2)  
Situated just to the west of the Gateway Bridge in Murarrie, Metroplex Wetlands are home to perhaps Brisbane's best-known pair of Peregrine Falcons, which nest high up on the bridge. Aside from the falcons, the site hosts a nice variety of waterbirds and is a real gem nestled within the surrounding industrial centres.  
Local Experts: Chris Attewell, Richard Miller.  

**[22. Sergeant Dan Stiller Memorial Reserve](https://ebird.org/australia/hotspot/L3185687)**  
158 Species | [27°38'38.2"S 153°00'11.3"E](https://goo.gl/maps/JCUfTLggKDJ2)  
Located in the extreme south of Brisbane near the border with Logan, Sergeant Dan Stiller Memorial Reserve is an area visited less than many of the sites above it on this list but nonetheless has a fantastic variety of birdlife. With increased visitation it is sure to turn up some interesting rarities, but already the site has boasted birds such as Cotton Pygmy-Goose, Glossy Black-Cockatoo and Jacky Winter.  
Local Experts: Tim and Marg Roberts.

**[23. Wynnum to Manly Foreshore](https://ebird.org/australia/hotspot/L2558660)**  
157 Species | [27°26'37.6"S 153°10'32.9"E](https://goo.gl/maps/ZNH2rAjrcCG2)  
Covering a large area of foreshore in Brisbane's south east, this site is excellent for shorebirds at low tide during summer, as well as several other species that inhabit the parks and esplanade along the shore. Pied Stilt, Australian Pied Oystercatcher and Masked Lapwing are all resident here, while migratory species including Eastern Curlew, Bar-tailed Godwit, Whimbrel and Pacific Golden-Plover are common in summer. Past vagrants include Radjah Shelduck, Sooty Tern and Australasian Gannet.  
Local Experts: Steve Cunningham, Richard Miller.

**[24. Wynnum Mangrove Boardwalk](https://ebird.org/australia/hotspot/L5009902)**  
156 Species | [27°25'30.4"S 153°10'08.2"E](https://goo.gl/maps/EH77dr4FjFk)  
_Note: This site has significant overlap with two other hotspots - Wynnum to Manly Foreshore and Lytton Wader Roost and Wynnum Mangrove Boardwalk. It is only treated here as a separate hotspot as this is how the sites are treated in eBird._  
The Wynnum Mangrove Boardwalk is an excellent location in south east Brisbane for observing shorebirds and mangrove specialist species, particularly at low tides when the waders are out feeding on the mudflats. Past rarities have included Cotton Pygmy-Goose, Asian Dowitcher and Jacky Winter.  
Local Experts: See overlapping hotspots.  

**[25. Swan Lake](https://ebird.org/australia/hotspot/L1367805)**  
155 Species | [27°23'29.8"S 153°10'04.4"E](https://goo.gl/maps/tMLsM2i88mE2)  
This aptly named lake, part of the Port of Brisbane, is home to hundreds of Black Swans, among many other wetland specialists. It is less frequently visited than the nearby shorebird roost, but nonetheless boasts a significant site list and several past vagrants. These include Black-necked Stork, Radjah Shelduck, Yellow-billed Spoonbill and White-winged Black Tern. The QWSG regularly conducts surveys here as well.  
Local Experts: Peter and Leith Woodall.

**[26. Sherwood Arboretum](https://ebird.org/australia/hotspot/L1007610)**  
154 Species |  [27°31'53.0"S 152°58'28.9"E](https://goo.gl/maps/w4BUbsaghrP2)  
A small pocket of Bushland on the Brisbane River, the Arboretum is a productive site with a decent variety of birdlife. Pale-vented Bush-hens are common here, as are White-headed Pigeons and Little Lorikeets - all uncommon species within Brisbane. Every now and then the site does turn up a rarity, although it is not as prone to such occurrences as other nearby sites.
Local Experts: Hugh Possingham, Mat Gilfedder.

**[27. Shorncliffe](https://ebird.org/australia/hotspot/L2559491)**  
153 Species | [27°19'41.5"S 153°05'05.1"E](https://goo.gl/maps/aV55tdU4n4z)  
North east Brisbane's sleepy seaside suburb, Shorncliffe boasts large expanses of mudflats suitable for migratory waders, a couple of suburban parks and the magnificent Shorncliffe Pier, a 350m long historic pier that juts out into the bay, providing one of the best seawatching locations on the mainland. Past rarities include numerous tern species, Lesser Frigatebird, Broad-billed Sandpiper and Australasian Gannet.  
Local Experts: Steve Murray, Jack Whiting.

**[28. Port of Brisbane Shorebird Roost](https://ebird.org/australia/hotspot/L984917)**  
152 Species | [27°22'32.4"S 153°11'02.3"E](https://goo.gl/maps/FQmF2145Va22)  
The fantastic Port of Brisbane Roost, maintained by the Port Authority, is a large open permanent roost that holds thousands of migratory shorebirds over summer and many more resident species as well. Access can be organised by visiting the Port's Visitor Centre and requesting a key (open during the week, weekend access is more difficult). It boasts quite the vagrant list, including Buff-breasted Sandpiper, Asian Dowitcher, Long-toed Stint, White-winged Black Tern and Australasian Shoveler. The QWSG regularly conducts surveys here as well.  
Local Experts: Chris Wiley, Elliot Leach.  

**[29. Anstead SES Depot](https://ebird.org/australia/hotspot/L3667263)**  
151 Species |  [27°33'27.3"S 152°51'24.7"E](https://goo.gl/maps/J7oHT388xcP2)  
An excellent example of how even the most unlikely locations can be birding gems, the SES Depot on Hawkesbury Rd in Anstead boasts quite the site list, with a number of vagrant species. In the past it has turned up Plum-headed Finch, Oriental Cuckoo and Scaly-breasted Munia, among other woodland species not commonly seen.  
Local Experts: Rod Gardner.

**[30. Moggill Conservation Park](https://ebird.org/australia/hotspot/L956652)**  
148 Species | [27°31'15.3"S 152°51'41.7"E](https://goo.gl/maps/5WfUzTNtEqC2)  
A large area of remnant bushland habitat in the western suburb of Moggill, this is a site which would almost certainly benefit from increased survey effort by Brisbane's birders. Easily accessible off Mt Crosby Rd, it is near several other fantastic birding locations, including Anstead Bushland, Anstead SES Depot and Hawkesbury Rd Nature Reserve. Past notable species include Black-breasted Buttonquail (which may still be present in small numbers), Turquoise Parrot, Barred Cuckooshrike, Major Mitchell's Cockatoo and Red-winged Parrot. This is an excellent site for inland vagrants to turn up during dry conditions!  
Local Experts: Rod Gardner, Jane Turnbull, Mat Gilfedder.

**[31. Mookin-Bah Reserve](https://ebird.org/australia/hotspot/L3807542)**  
148 Species | [27°28'49.6"S 153°10'38.8"E](https://goo.gl/maps/Yae3fVSCJ2B2)  
At the extreme south east edge of Brisbane, near the border with the Redlands lies Mookin-Bah Reserve, a large expanse of wetland and woodland habitat that is quickly proving to be an excellent birding hotspot. Aside from Sandy Camp, this is the only other regular location in Brisbane for Black Bittern, although the species has not been seen recently at the site. Other notable birds include crakes and rails, Little Wattlebird and Little Grassbird. This site is a relatively new birding discovery - there's plenty more to be found!  
Local Experts: Michael Daley.

**[32. Bellbird Grove](https://ebird.org/australia/hotspot/L1517847)**  
146 Species | [27°25'27.0"S 152°54'10.0"E](https://goo.gl/maps/chqtRepvYiE2)  
Situated at the end of the Camel's Back in north west Brisbane, just up the road from the Gap is Bellbird Grove, an excellent wet sclerophyll birding location with a great variety of species. This is the only reliable location in Brisbane for Spotted Quail-thrush, which can be found with some planning and diligent effort. Other good birds regularly seen include Little Lorikeet, White-bellied Cuckooshrike and Rose Robin; notable rarities include Oriental Cuckoo, Square-tailed Kite, Satin Flycatcher and Yellow Thornbill. This is a great site for rare birds to turn up on the odd occasion.  
Local Experts: Alan Boardman, Sue Lee.

**[33. Manly Wader Roost](https://ebird.org/australia/hotspot)**  
145 Species | [27°27'16.6"S 153°11'37.6"E](https://goo.gl/maps/9Jqcv7SZMqy)  
An excellent artificial shorebird roost built onto the end of the Manly RQYS Marina, access to this site is strictly controlled by the state government. The best option for access is through Birds Queensland and the QWSG; the Wader Studies Group run monthly shorebird surveys here as well as regular introductory wader ID days etc. which are open to BQ/QWSG members. There are many great birds regularly at this site, including Broad-billed Sandpiper, Grey Plover, Red Knot and Black-tailed Godwit, while vagrants in the past have included White-winged Black Tern, Asian Dowitcher, South Island Pied Oystercatcher, Wandering Tattler and Gould's Petrel.  
Local Experts: Sandra Harding, Colin Reid, Brad Woodworth.

**[34. Kedron Brook Bikeway](https://ebird.org/australia/hotspot/L2559157)**  
144 Species | [27°22'48.1"S 153°06'13.1"E](https://goo.gl/maps/9Wuvj8irhyoqyMEt7)  
This hotspot encompasses the entire bikeway that follows Kedron Brook from Toombul to Nudgee Rd, and covers a wide variety over habitats along its length. Several nice species have been reported here, including old records of Grey-crowned Babbler, King Quail, Red-rumped Parrot, and several nice shorebirds. The entire bikeway can also be walked, but is best travelled on bike, stopping every couple of hundred minutes to scan for birds.  
Local Experts: Steve Murray.

**[35. Hawkesbury Rd Nature Refuge](https://ebird.org/australia/hotspot/L2715036)**  
144 Species | [27°31'51.7"S 152°51'59.9"E](https://goo.gl/maps/Rfx5c6oxtqs)  
Adjacent to Moggill Conservation Park, the much smaller Hawkesbury Rd Nature Reserve nonetheless packs quite the birding punch, with many otherwise rare Brisbane species found here. An excellent network of trails runs through the park, although be prepared for quite the walk as the area is very hilly. Notable species include Rose-crowned Fruit-Dove, Square-tailed Kite, Spotted Quail-thrush, Painted Buttonquail, Little Bronze-Cuckoo, Russet-tailed Thrush, Oriental Cuckoo, Grey Goshawk and Black-chinned Honeyeater - quite the list!  
Local Experts: Rod Gardner.

**[36. Lytton and south west Fisherman Island](https://ebird.org/australia/hotspot/L2558847)**  
142 Species | [27°24'49.0"S 153°09'10.2"E](https://goo.gl/maps/8ixXSauzaWi7UZAG8)  
Another highly ambiguous hotspot on the south east bayside, this region is home to several good birding sites, all of which have their own specific hotspots which should be preferenced by future eBirders. This site is included here for posterity.  
Local Experts: Peter Woodall, Leith Woodall.

**[37. Cliveden Reserve](https://ebird.org/australia/hotspot/L1204082)**  
141 Species | [27°33'03.7"S 152°59'30.1"E](https://goo.gl/maps/Dcm1vsod1kH2)  
Across Oxley Creek from the Common lies Cliveden Reserve, a smaller sibling to the massive OCC, but a nonetheless great birding location. Past rare species at the site include White-bellied Cuckooshrike, Black-necked Stork, Scaly-breasted Munia and Rose-crowned Fruit-Dove.  
Local Experts: Hugh Possingham.

**[38. Banks St Reserve](https://ebird.org/australia/hotspot/L2558675)**  
140 Species | [27°26'04.5"S 152°59'51.1"E](https://goo.gl/maps/PJQEtGuBvZBwKDDCA)  
A fantastic site which is only just now having its true potential realised, Banks St Reserve is situated within the inner northside suburb of Ashgrove/Alderley and has already had some fantastic species recorded on the site list. Birds reported recently include White-bellied Cuckooshrike, White-throated Nightjar, Superb Fruit-Dove, Painted Buttonquail and Satin Flycatcher, while older records include species such as Scaly-breasted Munia, White-winged Triller and White-throated Treecreeper. Definitely a site to visit!  
Local Experts: Matteo Grilli.

**[39. JC Slaughter Falls](https://ebird.org/australia/hotspot/L966780)**  
138 Species | [27°28'34.4"S 152°57'49.7"E](https://goo.gl/maps/197owCckYc1skp417)  
Best known for its regular pair of Powerful Owls, the JC Slaughter Falls at the base of Mt Coot-tha have long been popular with birders. Notable species recorded here include the aforementioned owls, White-throated Nightjar, Spotted Quail-thrush, Scarlet Robin, Oriental Cuckoo and Rose-crowned Fruit-Dove.  
Local Experts: Mat Gilfedder.  

**[40. Whites Hill Reserve](https://ebird.org/australia/hotspot/L2560211)**  
138 Species | [27°30'38.4"S 153°04'58.6"E](https://goo.gl/maps/px4o2LbhKZ6vRWW39)  
Another site which is only just having its secrets uncovered, Whites Hill Reserve is a moderate-sized patch of remnant bushland situated in the inner southside. Notable species recorded here include Powerful Owl, White-bellied Cuckooshrike, Spotted Harrier, Oriental Cuckoo, Western Gerygone (only Brisbane record!), Little Woodswallow and Weebill.

_Species counts last updated 23rd May 2019._
