# Methods

The Atlas is built around data pulled from [eBird](https://ebird.org/home), an open access citizen science project run by the [Cornell Lab of Ornithology](http://www.birds.cornell.edu). The dataset comprises all validated wild bird records from within the Brisbane Local Government Area and any offshore point within Australia's Exclusive Economic Zone that has the Brisbane LGA as its closest point on land, as per current eBird protocol. This includes reports of escapees and feral introduced birds, as well as natives and vagrants. The entirety of the survey area is divided up into 4km^2^ squares for distribution mapping purposes; each square has a unique numerical code and land squares have unique names as well.

Data analysis is predominately done in the [R programming language](https://www.r-project.org/). The _Atlas_ is built around [R Markdown](https://rmarkdown.rstudio.com/), with additional sections in other languages - see the [GitHub](https://github.com/bird-team/brisbane-bird-atlas) and [wiki](https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#what-is-github) for more details. The _Atlas_ is updated with the latest version of the [eBird](https://ebird.org/home) dataset every few months or so, and is currently based on the `r data_release_month_year` release. The taxonomy followed is that of eBird's, while the common names used are those in the eBird Australian Common Names list.

Every species (and other taxonomic group treated separately within the _Atlas_) is allocated a category code, based on its presence status. These codes are loosely based on the [BOU classification](https://www.bou.org.uk/british-list/species-categories/) and are as follows:

A: A species that has occurred naturally in a wild state ever, regardless of date  
B: Redundant & unused  
C: Naturalised / introduced  
D: A species that likely only occurred as an escapee, but could in theory turn up wild  
E: Definite escapee  
F: Fossil records or records pre-1800  
G: Domestic types, regardless of wild/escapee status  
H: Hybrids   
X/Pending: Category pending  

For further detailed information on the _Atlas's_ methodology, please contact one of the editors.

**Footnote: Offshore Birding**

The _Atlas_ includes all records from [eBird](https://ebird.org/home) that are within the boundary of the Brisbane Local Government Area, or those which have Brisbane as their closest point of land. Strictly speaking, the Brisbane LGA area does not extend beyond the low-water mark, but instead "[comprises the mainland and the whole of Fisherman, Green, Mud and St Helena Islands (being islands situated in or adjacent to Moreton Bay) above the low-water mark](http://qldspatial.information.qld.gov.au/catalogue/custom/viewMetadataDetails.page?uuid=%7B3F3DBD69-647B-4833-B0A5-CC43D5E70699%7D)." For the purposes of the _Atlas_ however, the Brisbane LGA has been extended out to the edge of Australia's Exclusive Economic Zone, 200 nautical miles out from the coast.

The issue of coastal waters and sovereignty - at a local, state, federal and international level - is a complicated one, but for the sake of consistency and to ensure seabirds are covered in this _Atlas_ too, the decision was made to follow eBird protocol and use the closest point of land as the record's identifying location. Please contact one of the _Atlas_ editors if you have further queries about the survey area and its boundaries.
