# Species Accounts

The following pages contain species accounts for all birds known to have occurred in Brisbane and the adjacent offshore waters. Species accounts include details on the bird's distribution and occurrence patterns within the LGA, as well as audio and images of the birds. Brief descriptive notes and information on conservation needs for each species are also included.

Please see the [Contributing](https://brisbanebirds.com/contributing.html) page for details on how you can help write this atlas. Currently only a handful of species have draft accounts written - we need more writers!

Species with draft accounts: 24

- [Magpie Goose](https://brisbanebirds.com/magpie-goose-anseranas-semipalmata.html)
- [Plumed Whistling-Duck](http://brisbanebirds.com/plumed-whistling-duck-dendrocygna-eytoni.html)
- [Black Swan](http://brisbanebirds.com/black-swan-cygnus-atratus.html)
- [Pacific Black Duck](https://brisbanebirds.com/pacific-black-duck-anas-superciliosa.html)
- [Australian Brushturkey](http://brisbanebirds.com/australian-brush-turkey-alectura-lathami.html)
- [Australian Owlet-nightjar](http://brisbanebirds.com/australian-owlet-nightjar-aegotheles-cristatus.html)
- [Australian Swiftlet](http://brisbanebirds.com/australian-swiftlet-aerodramus-terraereginae.html)
- [Common Sandpiper](http://brisbanebirds.com/common-sandpiper-actitis-hypoleucos.html)
- [Grey Goshawk](https://brisbanebirds.com/grey-goshawk-accipiter-novaehollandiae.html)
- [Brown Goshawk](http://brisbanebirds.com/brown-goshawk-accipiter-fasciatus.html)
- [Collared Sparrowhawk](http://brisbanebirds.com/collared-sparrowhawk-accipiter-cirrocephalus.html)
- [Green Catbird](http://brisbanebirds.com/green-catbird-ailuroedus-crassirostris.html)
- [Eastern Spinebill](https://brisbanebirds.com/eastern-spinebill-acanthorhynchus-tenuirostris.html)
- [Spiny-cheeked Honeyeater](https://brisbanebirds.com/spiny-cheeked-honeyeater-acanthagenys-rufogularis.html)
- [Yellow-rumped Thornbill](https://brisbanebirds.com/yellow-rumped-thornbill-acanthiza-chrysorrhoa.html)
- [Yellow Thornbill](https://brisbanebirds.com/yellow-thornbill-acanthiza-nana.html)
- [Striated Thornbill](https://brisbanebirds.com/striated-thornbill-acanthiza-lineata.html)
- [Brown Thornbill](http://brisbanebirds.com/brown-thornbill-acanthiza-pusilla.html)
- [Buff-rumped Thornbill](http://brisbanebirds.com/buff-rumped-thornbill-acanthiza-reguloides.html)
- [Cicadabird](http://brisbanebirds.com/cicadabird-edolisoma-tenuirostre.html)
- [White-breasted Woodswallow](https://brisbanebirds.com/white-breasted-woodswallow-artamus-leucorynchus.html)
- [Spangled Drongo](http://brisbanebirds.com/spangled-drongo-dicrurus-bracteatus.html)
- [Australian Reed-Warbler](http://brisbanebirds.com/australian-reed-warbler-acrocephalus-australis.html)
- [Common Myna](http://brisbanebirds.com/common-myna-acridotheres-tristis.html)

```{r}
clear_page()
```
